### ISSUE TITLE
Publishing successful flaky/rerun results only

### ISSUE THREAD

**Issue by eparubrub-view** [allankp/pytest-testrail#100]
Currently, I have a couple test cases that are flaky and use the mark "@pytest.mark.flaky" in order to rerun the test cases that fail once in a while. After the rerun, some test cases will pass (meaning the case failed first and passed on the rerun), but the current functionality of pytest-testrail will publish the failed run on top (meaning the test case will be marked as failed as a whole). Is there a way to publish the passed run first or a way to only published the passed run? If not, I would like to request a feature for this. Overall, I would like to publish the test case as passed if one of the reruns succeeds.

**Comment by allankp** [comment]
This has been resolved in : https://github.com/allankp/pytest-testrail/pull/108

**Comment by wswiatkowski** [comment]
Hi! I'm using pytest-rerunfailures plugin in my test suite. Issue mentioned in this topic is still occurring in my test suite, so I have a FAILED status on tests which are rerunned - even if they PASSED in the second try. Could you address this issue?
